[package]
name = "password-trainer"
version = "0.1.0"
authors = ["cyd3r <cyd3rhacker@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
dialoguer = "0.8.0"
rand = "0.8.0"
ring = "0.16.20"
